# Generated by Django 4.1.7 on 2023-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookId',
            field=models.BigIntegerField(default=0),
        ),
    ]
