# Generated by Django 4.1.7 on 2023-03-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bookId',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
