# Generated by Django 4.1.7 on 2023-03-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
